StartupEvents.registry('item', event => {
    event.create('twilight_crystal')
        .tooltip(Text.translatable('tooltip.kubejs.twilight_crystal'))
        .rarity('uncommon')
})

StartupEvents.registry('block', event => {
    // 火卫二
    event.create('deimos_stone')
        .stoneSoundType()
        .fullBlock(true)
        .hardness(2)
        .requiresTool()
        .tagBlock("mineable/pickaxe")
    event.create('deimos_surface')
        .stoneSoundType()
        .fullBlock(true)
        .hardness(2)
        .requiresTool()
        .tagBlock("mineable/pickaxe")

    // 谷神星
    event.create('ceres_stone')
        .stoneSoundType()
        .fullBlock(true)
        .hardness(2)
        .requiresTool()
        .tagBlock("mineable/pickaxe")
    event.create('ceres_surface')
        .stoneSoundType()
        .fullBlock(true)
        .hardness(2)
        .requiresTool()
        .tagBlock("mineable/pickaxe")

    // 木卫三
    event.create('ganymede_stone')
        .stoneSoundType()
        .fullBlock(true)
        .hardness(2)
        .requiresTool()
        .tagBlock("mineable/pickaxe")
    event.create('ganymede_surface')
        .stoneSoundType()
        .fullBlock(true)
        .hardness(2)
        .requiresTool()
        .tagBlock("mineable/pickaxe")

    // 木卫一
    event.create('io_stone')
        .stoneSoundType()
        .fullBlock(true)
        .hardness(2)
        .requiresTool()
        .tagBlock("mineable/pickaxe")
    event.create('io_surface')
        .stoneSoundType()
        .fullBlock(true)
        .hardness(2)
        .requiresTool()
        .tagBlock("mineable/pickaxe")
    event.create('io_ash')
        .sandSoundType()
        .fullBlock(true)
        .hardness(2.6)
        .tagBlock("mineable/shovel")
})