GTCEuStartupEvents.registry('gtceu:tag_prefix', event => {
    event.create('moon_stone', 'ore')
        .stateSupplier(() => Block.getBlock('ad_astra:moon_stone').defaultBlockState())
        .baseModelLocation('ad_astra:block/moon_stone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
    
    event.create('venus_stone', 'ore')
        .stateSupplier(() => Block.getBlock('ad_astra:venus_stone').defaultBlockState())
        .baseModelLocation('ad_astra:block/venus_stone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
    
    event.create('mars_stone', 'ore')
        .stateSupplier(() => Block.getBlock('ad_astra:mars_stone').defaultBlockState())
        .baseModelLocation('ad_astra:block/mars_stone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
    
    event.create('mercury_stone', 'ore')
        .stateSupplier(() => Block.getBlock('ad_astra:mercury_stone').defaultBlockState())
        .baseModelLocation('ad_astra:block/mercury_stone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
    
    event.create('glacio_stone', 'ore')
        .stateSupplier(() => Block.getBlock('ad_astra:glacio_stone').defaultBlockState())
        .baseModelLocation('ad_astra:block/glacio_stone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)

    event.create('holystone', 'ore')
        .stateSupplier(() => Block.getBlock('aether:holystone').defaultBlockState())
        .baseModelLocation('aether:block/holystone')
        .unificationEnabled(true)
        .materialIconType(GTMaterialIconType.ore)
        .generationCondition(ItemGenerationCondition.hasOreProperty)
})