GTCEuStartupEvents.registry('gtceu:world_gen_layer', event => {
    event.create('ad')
        .targets(
            'ad_astra:moon_stone', 
            'ad_astra:venus_stone', 
            'ad_astra:mars_stone', 
            'ad_astra:mercury_stone', 
            'ad_astra:glacio_stone', 
            'minecraft:stone',
            'minecraft:deepslate', 
            'minecraft:blackstone', 
            'minecraft:basalt', 
            'minecraft:soul_soil'
        )
        .dimensions(
            'ad_astra:moon',
            'ad_astra:venus',
            'ad_astra:mars',
            'ad_astra:mercury',
            'ad_astra:glacio'
        )
    
    event.create('tf')
        .targets('minecraft:stone')
        .dimensions('twilightforest:twilight_forest')

    event.create('aether')
        .targets('aether:holystone')
        .dimensions('aether:the_aether')

    event.create('all')
        .targets(
            '#minecraft:stone_ore_replaceables',
            '#minecraft:deepslate_ore_replaceables',
            '#forge:end_stone_ore_replaceables',
            'ad_astra:moon_stone', 
            'ad_astra:venus_stone', 
            'ad_astra:mars_stone', 
            'ad_astra:mercury_stone', 
            'ad_astra:glacio_stone',
            'aether:holystone'
        )
        .dimensions(
            'minecraft:overworld',
            'minecraft:the_nether',
            'minecraft:the_end',
            'twilightforest:twilight_forest',
            'ad_astra:moon',
            'ad_astra:venus',
            'ad_astra:mars',
            'ad_astra:mercury',
            'ad_astra:glacio',
            'aether:the_aether'
        )
})